// The commit and branch rules, as specs/002-commit-rules/design.md states them.
export const TYPES = [
  'feat',
  'fix',
  'docs',
  'style',
  'refactor',
  'perf',
  'test',
  'build',
  'ci',
  'chore',
  'revert',
];

export const SCOPES = [
  'tokens',
  'styles',
  'angular',
  'icons',
  'metadata',
  'schematics',
  'mcp-server',
  'eslint-plugin',
  'stylelint-plugin',
  'docs',
  'workbench',
  'e2e',
  'repo',
  'ci',
  'deps',
];

export const HEADER_MAX_LENGTH = 72;
export const BODY_MAX_LINES = 2;
export const BRANCH_MAX_LENGTH = 50;

export const HEADER =
  /^(?<type>[a-z]+)(?:\((?<scope>[^()]+)\))?: (?<subject>.+)$/;

// Messages git writes itself.
export const MESSAGE_PASS_THROUGH = [
  /^Merge /,
  /^Revert "/,
  /^fixup! /,
  /^squash! /,
];

export const BRANCH_PASS_THROUGH = [/^main$/, /^changeset-release\//];

export const TRAILERS = [
  /^Co-Authored-By:/i,
  /^Signed-off-by:/i,
  /^Generated with/i,
  /^Generated by/i,
  // A tool or model name followed by a version, for example "Claude Opus 5".
  /\b(claude|opus|sonnet|haiku|gpt|copilot|codex|gemini|cursor)\b[^\n]*?\bv?\d/i,
];

const SLUG = '[a-z0-9]+(?:-[a-z0-9]+)*';
export const BRANCH_SPEC = new RegExp(`^\\d{3}-${SLUG}$`);
export const BRANCH_OTHER = new RegExp(`^(?:${TYPES.join('|')})/${SLUG}$`);
